### ISSUE TITLE
Issue deploying kit regarding ACL permissions

### ISSUE THREAD

**Issue by aws-pablito** [aws-samples/aws-rtb-intelligence-kit#20]
Getting the following issue when trying to deploy the stack:

`10:38:43 PM | CREATE_FAILED        | AWS::S3::Bucket                                    | sagemakeremrproductaccesslogsB5574FA3
Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: TVF9KW4TZ91KM9
00; S3 Extended Request ID: Z0du01ReoOWjKu9VQC0mvlhqaFACbWBp2IJcommNY7Do/aDxTBqtzYd9iZjUrPkSkRJFvVJi0eM=; Proxy: null)
`

Seems the kit is referencing an old way to assign ACL permissions according to https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-ownership-error-responses.html

**Comment by aws-pablito** [comment]
As a workaround, I remove Access Logging on the buckts. The way we are enabeling access logging on the buckets seems to sue ACLs instead of policies and seems is what is causing the issue.  See: https://github.com/aws/aws-cdk/issues/19603.   Seems to be related to this.. still troubleshooting

**Comment by balabad** [comment]
Thanks for reporting this @aws-pablito! I updated the logging bucket permissions mechanism from ACL to bucket policies.
